#!/usr/bin/env bash
set -euo pipefail

APK="${1:-Photo-TV.apk}"
OUT="${2:-android-visual-results}"
PACKAGE="fr.wokgui.phototv"
ACTIVITY=".MainActivity"

mkdir -p "$OUT"
adb wait-for-device
adb shell settings put global window_animation_scale 0 || true
adb shell settings put global transition_animation_scale 0 || true
adb shell settings put global animator_duration_scale 0 || true
adb shell wm size 1280x720 || true
adb shell wm density 160 || true
adb logcat -c || true

# Instrumentation tests may have installed a test-signed debug build. Remove it before
# installing the exact APK artifact produced by the build job.
adb uninstall "$PACKAGE" >/dev/null 2>&1 || true
adb install "$APK"

state_log() {
  adb logcat -d -s PhotoTVState:I '*:S' | tail -n 80
}

latest_state() {
  state_log | tail -n 1
}

assert_state() {
  local needle="$1"
  local state
  state="$(latest_state)"
  echo "$state"
  if ! grep -Fq "$needle" <<<"$state"; then
    echo "Expected UI state not found: $needle" >&2
    state_log >&2
    exit 1
  fi
}

assert_foreground() {
  local top
  top="$(adb shell dumpsys activity activities | grep -E 'mResumedActivity|topResumedActivity' | head -n 1 || true)"
  echo "$top"
  grep -Fq "$PACKAGE" <<<"$top" || {
    echo "Photo TV is not the foreground activity." >&2
    exit 1
  }
}

start_page() {
  local page="$1"
  adb shell am force-stop "$PACKAGE" >/dev/null 2>&1 || true
  adb shell am start -W -n "$PACKAGE/$ACTIVITY" \
    --ez phototv_test_mode true \
    --ei phototv_test_page "$page" >/tmp/photo-tv-start.txt
  sleep 1.0
  assert_foreground
  assert_state "page=$page"
}

capture_page() {
  local index="$1"
  local name="$2"
  start_page "$index"
  adb shell screencap -p "/sdcard/${name}.png"
  adb pull "/sdcard/${name}.png" "$OUT/${name}.png" >/dev/null
  echo "captured Android TV $name"
}

# Real installed APK screenshots used by the visual regression gate.
capture_page 0 preview
capture_page 1 photos
capture_page 2 editor
capture_page 3 settings

# Reinstall the exact same final APK in place. If the signer changes between builds
# generated by the same signing mode, this is where Android rejects the update.
adb install -r "$APK"
start_page 0
assert_foreground
assert_state "page=0"

adb shell dumpsys package "$PACKAGE" > "$OUT/package-dump.txt"
adb shell pm path "$PACKAGE" > "$OUT/package-path.txt"
state_log > "$OUT/automation-state-log.txt"

if adb logcat -d | grep -E "FATAL EXCEPTION|AndroidRuntime" | grep -Fq "$PACKAGE"; then
  adb logcat -d | grep -E "FATAL EXCEPTION|AndroidRuntime|$PACKAGE" | tail -n 160
  echo "Crash detected during Android TV APK visual test." >&2
  exit 1
fi

echo "Android TV APK screenshots and in-place reinstall test passed."
